#!/bin/bash

PS3='Select the server you want to run: '
options=("Primary #1" "Primary #2" "Backup #1" "Backup #2" "Quit")
select opt in "${options[@]}"
do
    case $opt in
        "Primary #1")
            ./server -fprimary1.cfg -d
            ;;
        "Primary #2")
            ./server -fprimary2.cfg -d
            ;;
        "Backup #1")
            ./server -fbackup1.cfg -d
            ;;
        "Backup #2")
            ./server -fbackup2.cfg -d
            ;;
        "Quit")
            break
            ;;
        *) echo Invalid option;;
    esac
done
